---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp courses.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp collaboration.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assests $DEPLOYPATH
